---

- name: Pause for 20 seconds to let service start
  ansible.builtin.pause:
    seconds: 20

- name: Validate service is accessible
  delegate_to: localhost
  ansible.builtin.uri:
    url: http://{{ inventory_hostname }}:8080
    return_content: true
  register: tomcat_results
  # failed_when: tomcat_result is failed or "'Ansible' not in tomcat_results.content"

- name: Update service_notes
  ansible.builtin.set_fact:
        service_notes: "{{ service_notes + tomcat_results.invocation | to_nice_yaml }}"

- name: Close problem
  delegate_to: localhost
  ansible.builtin.uri:
    url: "{{ dt_api_host }}/api/v2/problems/{{ ansible_eda.event.problemId }}/close"
    method: POST
    status_code: [200, 202, 204]
    headers:
      Content-Type: application/json
      Authorization: "Api-Token {{ dt_api_token }}"
    body: '{"message": "Closed by Ansible after validating service was restored \n {{ tomcat_results.invocation }}"}'