---
- name: Close Problem in Dynatrace
  hosts: localhost
  gather_facts: False
  become: False
  tasks:
    - name: Close problem in Dynatrace
      ansible.builtin.uri:
        url: "{{ dt_api_host }}/api/v2/problems/{{ ansible_eda.event.problemId }}/close"
        method: POST
        status_code: [200, 202, 204]
        headers:
          Content-Type: application/json
          Authorization: "Api-Token {{ dt_api_token }}"
        body: '{"message": "Closed by Ansible after validating service was restored \n {{ service_notes }}"}'