---
- name: Create an incident ticket in ServiceNow
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create incident
      tags:
        - create
        - never
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        caller: splunk_ansible_workflow
        short_description: "{{ ansible_eda.event.title }}: {{ ansible_eda.event.affectedEntities[0].name }}"
        description: "{{ ansible_eda | to_nice_yaml }}"
        impact: medium
        urgency: medium
      register: incident_out

    - name: Change state of the incident
      tags:
        - in_progress
        - never
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ ServiceNow_Incident_Number }}"
        state: in_progress

    - name: Update the incident
      tags:
        - update
        - never
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ ServiceNow_Incident_Number }}"
        work_notes: "Adding in some work nodes"

    - name: Close incident
      tags:
        - close
        - never
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ ServiceNow_Incident_Number }}"
        state: closed
        close_code: "Solved (Permanently)"
        close_notes: "{{ service_notes }}"

    - name: servicenow update notes

    - name: Set Incident Number
      tags:
        - always
      when: incident_out is defined
      ansible.builtin.set_stats:
        data:
          ServiceNow_Incident_Number: "{{ incident_out.record.number }}"