---
- name: Service Down - Restart Service
  hosts: "{{ ansible_eda.event.impactedEntities[0].entityId.id }}"
  #hosts: "{{ _hosts }}"
  become: true
  gather_facts: False

  tasks:
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: "{{ ansible_eda.event.impactedEntities[0].name }}"
        state: started
